server:
  port: 8080
spring:
  application:
    name: clinic-test
  sql:
    init:
      platform: mysql
  datasource:
    hikari:
      maximumPoolSize: 100
    url: ${db.url}?currentSchema=${db.schema}
    username: ${db.username}
    password: ${db.password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

security:
  jwt:
    secret-key: ''
    expiration-time-minutes: 1440 # 24 hours
admin-doctor:
  email: admin@test.com
  password: 12345
