server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: clinic-test
  sql:
    init:
      platform: mysql
  datasource:
    hikari:
      maximumPoolSize: 100
    url:  jdbc:mysql://localhost:3306/clinic?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

security:
  jwt:
    secret-key: '53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855'
    expiration-time-minutes: 1440 # 24 hours
init-data:
  admin-doctor:
    email: admin@achme.com
    password: 12345
    firstName: Admin
    lastName: Admin
  clinic-default:
    auto-create: true
    name: 'Achme Clinic'
    email: 'achme.clinic@email.com'
    phone: 123456789
    from-hour: 9
    to-hour: 20
    logo-url: 'classpath:static/images/clinic-logo.png'
jobs:
  close-appointments-cron: 0 0 0 * * ? # every day at midnight

