server:
  port: 8080
spring:
  application:
    name: clinic-test
  sql:
    init:
      platform: mysql
  datasource:
    hikari:
      maximumPoolSize: 100
    url: ${db.url}?currentSchema=${db.schema}
    username: ${db.username}
    password: ${db.password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

security:
  jwt:
    secret-key: ''
    expiration-time-minutes: 1440 # 24 hours
init-data:
  admin-doctor:
    email: admin@test.com
    password: 12345
    firstName: admin
    lastName: admin
  clinic-default:
    auto-create: true
    name: 'Achme Clinic'
    email: 'achme.clinic@email.com'
    phone: 123456789
    from-hour: 9
    to-hour: 20
    logo-url: 'classpath:static/images/clinic-logo.png'

